language: node_js
node_js: stable

cache:
    apt: true
    directories:
        - node_modules

before_install:
    - npm install hexo-cli -g

install:
  - npm install

script:
  - npm run deploy

after_script:
  - git config user.name "jovysun"
  - git config user.email "jovysun@163.com"

branches:
  only:
    - master